<a href="https://colab.research.google.com/github/Kartik-Koul/ConvoAI-Basic_Numpy/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1.** (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
rev = np.flip(arr)

print("Original array : ", str(arr))
print("Reversed array : ", str(rev))

Original array :  [1 2 3 6 4 5]
Reversed array :  [5 4 6 3 2 1]


**Q1.** (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])

array2 = array1.flatten() #Flattening using the flatten() function
array3 = array1.ravel() #Flattening using the ravel() function

print("Original array : ",(array1))
print("Result using flatten() : ", str(array2))
print("Result using ravel() : ", str(array3))



Original array :  [[1 2 3]
 [2 4 5]
 [1 2 3]]
Result using flatten() :  [1 2 3 2 4 5 1 2 3]
Result using ravel() :  [1 2 3 2 4 5 1 2 3]


**Q1.** (c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

print(np.equal(arr1,arr2)) #Comparing individual elements

is_equal = arr1 == arr2
print(is_equal.all()) #Comparing entire arrays at once

[[ True  True]
 [ True  True]]
True


**Q1.** (d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

def return_modal_values(arr):
  arr_values, arr_counts = np.unique(arr, return_counts = True)
  mode_indices = np.argwhere(arr_counts == np.max(arr_counts))
  mode_values = arr_values[mode_indices].flatten().tolist()
  return mode_values

def print_modal_info(arr):
  arr_modes = return_modal_values(arr)
  print("Mode(s) for the given array are : ",arr_modes)
  print("Indices where the mode(s) is/are present respectively: ")
  for i in arr_modes:
    arr_modal_indices = np.where(arr == i)
    print(arr_modal_indices[0])

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

print("For array x:")
print_modal_info(x)
print()
print("For array y:")
print_modal_info(y)
#print(mode_values)
#print(np.count_nonzero(mode_values))


**Q1.** (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise


In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#SUM OF ALL ELEMENTS
print(np.sum(gfg))
print()
#SUM OF ELEMENTS ROW WISE
print(np.sum(gfg, axis=1))
print()
#SUM OF ELEMENTS COLUMN WISE
print(np.sum(gfg, axis=0))

45

[[14]
 [16]
 [15]]

[[20  9 16]]


**Q1.** (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [ ]:
import numpy as np
from numpy import linalg as la
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
#SUM OF DIAGONAL ELEMENTS
print(f"Sum of diagonal elements = {np.trace(n_array)}")
#EIGEN VALUES AND VECTORS OF MATRIX
eigenvalues, eigenvectors = la.eig(n_array)
print()
print("Eigen values = ",eigenvalues)
print("Eigen vectors = ",eigenvectors)
#INVERSE OF MATRIX
print()
print("Inverse of matrix: ")
print(la.inv(n_array))
#DETERMINANT OF MATRIX
print()
print("Determinant of matrix = ",la.det(n_array))

Sum of diagonal elements = 176

Eigen values =  [98.16835147 28.097044   49.73460452]
Eigen vectors =  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of matrix: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant of matrix =  137180.0000000001


**Q1.** (g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
import numpy as np

In [ ]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

p_arr = np.matrix(p)
q_arr = np.matrix(q)
# MULTIPLICATION
print(np.matmul(p_arr,q_arr))
# FINDING CO-VARIANCE
print(np.cov(p_arr,q_arr))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

p_arr = np.matrix(p)
q_arr = np.matrix(q)
# MULTIPLICATION
print(np.matmul(p_arr,q_arr))
# FINDING COVARIANCE
print(np.cov(p_arr,q_arr))

**Q1.** (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
import numpy as np
import itertools as it

x = np.array([[2,3,4],[3,2,9]])
y = np. array([[1,5,0],[5,10,3]])

print("Inner product = ",np.inner(x,y))
print()
print("Outer product = ",np.outer(x,y))
print()
cartprod = np.array(list(it.product(x,y)))
print("Cartesian product = ")
print(cartprod)

Inner product =  [[17 52]
 [13 62]]

Outer product =  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

[[[ 2  3  4]
  [ 1  5  0]]

 [[ 2  3  4]
  [ 5 10  3]]

 [[ 3  2  9]
  [ 1  5  0]]

 [[ 3  2  9]
  [ 5 10  3]]]


**Q2.** (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row.

In [ ]:
import numpy as np

array = np.array([[1,-2,3],[-4,5,-6]])

In [ ]:
print("Original array : ")
print(array)
print("Element-wise absolute values : ")
print(np.absolute(array))

In [ ]:
#DATA VALUES OF FLATTENED ARRAY
array_1 = array.flatten()
per1 = np.percentile(array_1,25)
per2 = np.percentile(array_1,50)
per3 = np.percentile(array_1,75)
print("25th percentile = ",per1)
print("50th percentile = ",per2)
print("75th percentile = ",per3)
print("Mean  = ",np.mean(array_1))
print("Median = ",np.median(array_1))
print("Standard Deviation = ",np.std(array_1))

25th percentile =  -3.5
50th percentile =  -0.5
75th percentile =  2.5
Mean  =  -0.5
Median =  -0.5
Standard Deviation =  3.8622100754188224


In [ ]:
#DATA VALUES OF EACH ROW
i = 1
for i in array:
  print(f"25th percentile of row {i} is {np.percentile(i,25)}")
  print(f"50th percentile of row {i} is {np.percentile(i,50)}")
  print(f"75th percentile of row {i} is {np.percentile(i,75)}")
  print(f"Mean of row {i} is {np.mean(i)}")
  print(f"Median of row {i} is {np.median(i)}")
  print(f"Standard Deviation of row {i} is {np.std(i)}")
  print()
  i = i + 1

25th percentile of row [ 1 -2  3] is -0.5
50th percentile of row [ 1 -2  3] is 1.0
75th percentile of row [ 1 -2  3] is 2.0
Mean of row [ 1 -2  3] is 0.6666666666666666
Median of row [ 1 -2  3] is 1.0
Standard Deviation of row [ 1 -2  3] is 2.0548046676563256

25th percentile of row [-4  5 -6] is -5.0
50th percentile of row [-4  5 -6] is -4.0
75th percentile of row [-4  5 -6] is 0.5
Mean of row [-4  5 -6] is -1.6666666666666667
Median of row [-4  5 -6] is -4.0
Standard Deviation of row [-4  5 -6] is 4.784233364802441



In [ ]:
#DATA VALUES OF EACH COLUMN
i = 1
array2 = np.transpose(array)
for i in array2:
  print(f"25th percentile of column {i} is {np.percentile(i,25)}")
  print(f"50th percentile of column {i} is {np.percentile(i,50)}")
  print(f"75th percentile of column {i} is {np.percentile(i,75)}")
  print(f"Mean of column {i} is {np.mean(i)}")
  print(f"Median of column {i} is {np.median(i)}")
  print(f"Standard Deviation of column {i} is {np.std(i)}")
  print()
  i = i + 1

25th percentile of column [ 1 -4] is -2.75
50th percentile of column [ 1 -4] is -1.5
75th percentile of column [ 1 -4] is -0.25
Mean of column [ 1 -4] is -1.5
Median of column [ 1 -4] is -1.5
Standard Deviation of column [ 1 -4] is 2.5

25th percentile of column [-2  5] is -0.25
50th percentile of column [-2  5] is 1.5
75th percentile of column [-2  5] is 3.25
Mean of column [-2  5] is 1.5
Median of column [-2  5] is 1.5
Standard Deviation of column [-2  5] is 3.5

25th percentile of column [ 3 -6] is -3.75
50th percentile of column [ 3 -6] is -1.5
75th percentile of column [ 3 -6] is 0.75
Mean of column [ 3 -6] is -1.5
Median of column [ 3 -6] is -1.5
Standard Deviation of column [ 3 -6] is 4.5



**Q2.** (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print(f"Floor value = {np.floor(a)}")
print(f"Ceiling values = {np.ceil(a)}")
print(f"Truncated values = {np.trunc(a)}")
print(f"Rounded values = {np.rint(a)}")

Floor value = [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values = [-1. -1. -0.  1.  2.  2.  3.]
Truncated values = [-1. -1. -0.  0.  1.  1.  3.]
Rounded values = [-2. -2. -0.  0.  2.  2.  3.]


**Q3.** (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16,54, 453])

In [ ]:
array1 = np.sort(array)
print(f"Sorted array = {array1}")

Sorted array = [ 10  16  16  52  54  62 453]


In [ ]:
print(f"Indices of sorted array = {np.argsort(array)}")

Indices of sorted array = [0 3 4 1 5 2 6]


In [ ]:
print(f"4 smallest elements = {array1[:4]}")

4 smallest elements = [10 16 16 52]


In [ ]:
print(f"5 largest elements = {array1[-1:-6:-1]}")

5 largest elements = [ 16  52  54  62 453]


**Q3.** (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [ ]:
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [ ]:
int_only_arr = array[array == array.astype(int)]
print(int_only_arr)

In [ ]:
int_only_arr = array[array != array.astype(int)]
print(int_only_arr)

**Q4.** (a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

(b) Load the saved file into jupyter notebook?

In [ ]:
!sudo apt install tesseract-ocr
!pip install pytesseract
!pip install Pillow==9.0.0
!pip install gTTS

In [ ]:
import pytesseract
from PIL import Image
import pygame
import gtts

pygame 2.5.0 (SDL 2.28.0, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [ ]:
def img_to_array(path):
  result = pytesseract.image_to_string(Image.open(path))
  f = open("file.txt","w")
  f.write(result)
  f.close()


In [ ]:
path = '/content/img.png'
img_to_array(path)

In [ ]:
f = open("file.txt","r")